# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "up-unstable-${version}";
  version = "2018-10-24";
  rev = "5bb81d216865514df0f864d89edb04bb4906ebb5";

  goPackagePath = "github.com/akavel/up";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/akavel/up";
    sha256 = "0nn37g52v85b89fyj5b5mjs3j6r1l0a06dm31vgl2m5lyx2h214k";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
