# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "rpool/nixos";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/EA1C-E08E";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "rpool/home";
      fsType = "zfs";
    };

  fileSystems."/home/aquagon" =
    { device = "rpool/home/aquagon";
      fsType = "zfs";
    };

  fileSystems."/home/svein" =
    { device = "rpool/home/svein";
      fsType = "zfs";
    };

  fileSystems."/home/svein/Anime" =
    { device = "rpool/home/svein/Anime";
      fsType = "zfs";
    };

  fileSystems."/home/svein/Documents" =
    { device = "rpool/home/svein/Documents";
      fsType = "zfs";
    };

  fileSystems."/home/svein/Games" =
    { device = "rpool/home/svein/Games";
      fsType = "zfs";
    };

  fileSystems."/home/svein/backups" =
    { device = "rpool/home/svein/backups";
      fsType = "zfs";
    };

  fileSystems."/home/svein/dcc" =
    { device = "rpool/home/svein/dcc";
      fsType = "zfs";
    };

  fileSystems."/home/svein/secure-encfs" =
    { device = "rpool/home/svein/secure-encfs";
      fsType = "zfs";
    };

  fileSystems."/home/svein/web" =
    { device = "rpool/home/svein/web";
      fsType = "zfs";
    };

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 8;
}
