# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "rpool/root";
      fsType = "zfs";
    };

  fileSystems."/etc" =
    { device = "rpool/root/etc";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "rpool/root/nix";
      fsType = "zfs";
    };

  fileSystems."/nix/store" =
    { device = "rpool/root/nix/store";
      fsType = "zfs";
    };

  fileSystems."/var" =
    { device = "rpool/root/var";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "rpool/home";
      fsType = "zfs";
    };

  fileSystems."/home/svein" =
    { device = "rpool/home/svein";
      fsType = "zfs";
    };

  fileSystems."/home/svein/old" =
    { device = "stash/home/svein";
      fsType = "zfs";
    };

  fileSystems."/home/svein/old/dev" =
    { device = "stash/nvmpool/dev";
      fsType = "zfs";
    };

  fileSystems."/home/svein/dev" =
    { device = "rpool/home/svein/dev";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/445F-2C55";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/cd7e6f53-0a73-42dc-987e-7dc3e751ebfc"; }
    ];

}
