---
- name: Deploy ComfyUI service
  template:
    src: comfyui.service.j2
    dest: /etc/systemd/system/comfyui.service
    mode: "0644"
  notify: restart comfyui

- name: Enable and start ComfyUI
  systemd:
    name: comfyui
    enabled: true
    state: started
    daemon_reload: true
