# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/home" =
    { device = "rpool/home";
      fsType = "zfs";
    };

  fileSystems."/home/svein" =
    { device = "rpool/home/svein";
      fsType = "zfs";
    };

  fileSystems."/home/svein/win" =
    { device = "rpool/home/svein/win";
      fsType = "zfs";
    };

  fileSystems."/home/minecraft" =
    { device = "rpool/home/minecraft";
      fsType = "zfs";
    };

  fileSystems."/home/minecraft/erisia" =
    { device = "rpool/home/minecraft/erisia";
      fsType = "zfs";
    };

  fileSystems."/home/minecraft/erisia/dynmap" =
    { device = "rpool/home/minecraft/erisia/dynmap";
      fsType = "zfs";
    };

  fileSystems."/home/minecraft/incognito" =
    { device = "rpool/home/minecraft/incognito";
      fsType = "zfs";
    };

  fileSystems."/home/minecraft/incognito/dynmap" =
    { device = "rpool/home/minecraft/incognito/dynmap";
      fsType = "zfs";
    };

  fileSystems."/home/bloxgate" =
    { device = "rpool/home/bloxgate";
      fsType = "zfs";
    };

  fileSystems."/home/darqen27" =
    { device = "rpool/home/darqen27";
      fsType = "zfs";
    };

  fileSystems."/home/david" =
    { device = "rpool/home/david";
      fsType = "zfs";
    };

  fileSystems."/home/dusk" =
    { device = "rpool/home/dusk";
      fsType = "zfs";
    };

  fileSystems."/home/jmc" =
    { device = "rpool/home/jmc";
      fsType = "zfs";
    };

  fileSystems."/home/kim" =
    { device = "rpool/home/kim";
      fsType = "zfs";
    };

  fileSystems."/home/lucca" =
    { device = "rpool/home/lucca";
      fsType = "zfs";
    };

  fileSystems."/home/luke" =
    { device = "rpool/home/luke";
      fsType = "zfs";
    };

  fileSystems."/home/mei" =
    { device = "rpool/home/mei";
      fsType = "zfs";
    };

  fileSystems."/home/prospector" =
    { device = "rpool/home/prospector";
      fsType = "zfs";
    };

  fileSystems."/home/simplynoire" =
    { device = "rpool/home/simplynoire";
      fsType = "zfs";
    };

  fileSystems."/home/vindex" =
    { device = "rpool/home/vindex";
      fsType = "zfs";
    };

  fileSystems."/home/will" =
    { device = "rpool/home/will";
      fsType = "zfs";
    };

  fileSystems."/home/xgas" =
    { device = "rpool/home/xgas";
      fsType = "zfs";
    };

  powerManagement.cpuFreqGovernor = lib.mkDefault "performance";
}
