# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot = {
    initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
    initrd.kernelModules = [ ];
    kernelModules = [ "kvm-amd" ];
    extraModulePackages = [ ];
  };

  fileSystems = {
    "/" = {
      device = "rpool/root";
      fsType = "zfs";
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/2E14-1ECC";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

    "/home" = {
      device = "rpool/home";
      fsType = "zfs";
    };

    "/home/svein" = {
      device = "rpool/home/svein";
      fsType = "zfs";
    };

    "/home/svein/AI/image-generation/models" = {
      device = "rpool/bulk/image-models";
      fsType = "zfs";
    };

    "/tsugumi" = {
      device = "svein@tsugumi.local:";
      fsType = "fuse.sshfs";
      options = [
        "noauto"
        "x-systemd.automount"
        "_netdev"
        "users"
        "idmap=user"
        "IdentityFile=/home/svein/.ssh/id_ed25519"
        "allow_other"
        "default_permissions"
        "uid=1000"
        "gid=100"
        "exec"
        "reconnect"
        "ServerAliveInterval=15"
        "ServerAliveCountMax=3"
      ];
    };
  };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/646c91c3-19dc-4066-aa3a-827649e3c837"; }
      { device = "/dev/disk/by-uuid/46a03ba7-f146-4b50-a756-5e22cabfcf4d"; }];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
