# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "rpool";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2CE6-0A91";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "rpool/home";
      fsType = "zfs";
    };

  fileSystems."/home/svein" =
    { device = "rpool/home/svein";
      fsType = "zfs";
    };

  fileSystems."/home/svein/mnt" = {
    device = "svein@brage.info:";
    fsType = "fuse.sshfs";
    options = [
      "noauto" "x-systemd.automount" "_netdev" "users" "idmap=user"
      "IdentityFile=/home/svein/.ssh/id_ed25519"
      "allow_other" "reconnect" "follow_symlinks" "default_permissions"
      "uid=1000" "gid=100"
    ];
  };

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 48;
}
