# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "sd_mod" "nvme" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "ssd/root";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A4C0-0C04";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "stash/home";
      fsType = "zfs";
    };

  fileSystems."/home/anne" =
    { device = "stash/home/anne";
      fsType = "zfs";
    };

  fileSystems."/home/svein" =
    { device = "ssd/home/svein";
      fsType = "zfs";
    };

  fileSystems."/home/znapzend" =
    { device = "stash/home/znapzend";
      fsType = "zfs";
    };

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 12;
  powerManagement.cpuFreqGovernor = "powersave";
}
