# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "zrepl-unstable-${version}";
  version = "0.1.1";
  rev = "v0.1.1";

  goPackagePath = "github.com/zrepl/zrepl";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/zrepl/zrepl";
    sha256 = "0b56i8w56p1bi9d4a5h5smizlx93vqk9d5rfpwv8ay2l0275d4y5";
  };

  goDeps = ./deps.nix;

  postInstall = ''
    for exe in example integration_test_variablereceiverate  microbenchmark  wireevaluator; do
      rm $bin/bin/$exe
    done
  '';

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
