# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
[
  {
    goPackagePath = "github.com/beorn7/perks";
    fetch = {
      type = "git";
      url = "https://github.com/beorn7/perks";
      rev = "4b2b341e8d7715fae06375aa633dbb6e91b3fb46";
      sha256 = "1i1nz1f6g55xi2y3aiaz5kqfgvknarbfl4f0sx4nyyb4s7xb1z9x";
    };
  }
  {
    goPackagePath = "github.com/fatih/color";
    fetch = {
      type = "git";
      url = "https://github.com/fatih/color";
      rev = "3f9d52f7176a6927daacff70a3e8d1dc2025c53e";
      sha256 = "165ww24x6ba47ji4j14mp3f006ksnmi53ws9280pgd2zcw91nbn8";
    };
  }
  {
    goPackagePath = "github.com/ftrvxmtrx/fd";
    fetch = {
      type = "git";
      url = "https://github.com/ftrvxmtrx/fd";
      rev = "c6d800382fff6dc1412f34269f71b7f83bd059ad";
      sha256 = "0ibzmf6nd83iz1r60v6q9a07swjyjbnwfx5zaxwvq5xvfpyxbbzg";
    };
  }
  {
    goPackagePath = "github.com/gdamore/encoding";
    fetch = {
      type = "git";
      url = "https://github.com/gdamore/encoding";
      rev = "6289cdc94c00ac4aa177771c5fce7af2f96b626d";
      sha256 = "1vmm5zll92i2fm4ajqx0gyx0p9j36496x5nabi3y0x7h0inv0pk9";
    };
  }
  {
    goPackagePath = "github.com/gdamore/tcell";
    fetch = {
      type = "git";
      url = "https://github.com/gdamore/tcell";
      rev = "b5d0c1ac570211e469f43ff88c0c6aa4b56cc99a";
      sha256 = "0g2zfbgyk3djlk0qpmrgcyy0ba9ad932yswpaacswi21qyf9gwag";
    };
  }
  {
    goPackagePath = "github.com/go-logfmt/logfmt";
    fetch = {
      type = "git";
      url = "https://github.com/go-logfmt/logfmt";
      rev = "07c9b44f60d7ffdfb7d8efe1ad539965737836dc";
      sha256 = "06smxc112xmixz78nyvk3b2hmc7wasf2sl5vxj1xz62kqcq9lzm9";
    };
  }
  {
    goPackagePath = "github.com/golang/protobuf";
    fetch = {
      type = "git";
      url = "https://github.com/golang/protobuf";
      rev = "e91709a02e0e8ff8b86b7aa913fdc9ae9498e825";
      sha256 = "16arbb7nwvs7lkpr7i9vrv8mk9h77zd3blzp3z9b0infqla4ddzc";
    };
  }
  {
    goPackagePath = "github.com/google/uuid";
    fetch = {
      type = "git";
      url = "https://github.com/google/uuid";
      rev = "c2e93f3ae59f2904160ceaab466009f965df46d6";
      sha256 = "0zw8fvl6jqg0fmv6kmvhss0g4gkrbvgyvl2zgy5wdbdlgp4fja0h";
    };
  }
  {
    goPackagePath = "github.com/jinzhu/copier";
    fetch = {
      type = "git";
      url = "https://github.com/jinzhu/copier";
      rev = "7e38e58719c33e0d44d585c4ab477a30f8cb82dd";
      sha256 = "03i7cz8aj42g0kp89myd0hdgzicyk0abfjxa7wcnpx5vlk6x0z0p";
    };
  }
  {
    goPackagePath = "github.com/kr/pretty";
    fetch = {
      type = "git";
      url = "https://github.com/kr/pretty";
      rev = "a0c635c0aede2cb0c2f8bb0f0d70485fbdd11bd4";
      sha256 = "190hy0zsrbrdirqayjj29mszplp176gqp52hbgw1wgw06myqy1rx";
    };
  }
  {
    goPackagePath = "github.com/kr/text";
    fetch = {
      type = "git";
      url = "https://github.com/kr/text";
      rev = "e2ffdb16a802fe2bb95e2e35ff34f0e53aeef34f";
      sha256 = "1gm5bsl01apvc84bw06hasawyqm4q84vx1pm32wr9jnd7a8vjgj1";
    };
  }
  {
    goPackagePath = "github.com/lucasb-eyer/go-colorful";
    fetch = {
      type = "git";
      url = "https://github.com/lucasb-eyer/go-colorful";
      rev = "30298f24079860c4dee452fdef6519b362a4a026";
      sha256 = "0fig06880bvk1l92j4127v4x9sar4ds7ga8959gxxghb2w70b7l2";
    };
  }
  {
    goPackagePath = "github.com/mattn/go-colorable";
    fetch = {
      type = "git";
      url = "https://github.com/mattn/go-colorable";
      rev = "3a70a971f94a22f2fa562ffcc7a0eb45f5daf045";
      sha256 = "0l640974j804c1yyjfgyxqlsivz0yrzmbql4mhcw2azryigkp08p";
    };
  }
  {
    goPackagePath = "github.com/mattn/go-isatty";
    fetch = {
      type = "git";
      url = "https://github.com/mattn/go-isatty";
      rev = "c1975dc15c1d481e8da23f6ed313bb071136b98f";
      sha256 = "0p4psaxzs02snlqqhldkpkmsksp1rr48541rwzi8qbrapn4lbfwd";
    };
  }
  {
    goPackagePath = "github.com/mattn/go-runewidth";
    fetch = {
      type = "git";
      url = "https://github.com/mattn/go-runewidth";
      rev = "703b5e6b11ae25aeb2af9ebb5d5fdf8fa2575211";
      sha256 = "0znpyz71gajx3g0j2zp63nhjj2c07g16885vxv4ykwnrfmzbgk4w";
    };
  }
  {
    goPackagePath = "github.com/matttproud/golang_protobuf_extensions";
    fetch = {
      type = "git";
      url = "https://github.com/matttproud/golang_protobuf_extensions";
      rev = "c182affec369e30f25d3eb8cd8a478dee585ae7d";
      sha256 = "1xqsf9vpcrd4hp95rl6kgmjvkv1df4aicfw4l5vfcxcwxknfx2xs";
    };
  }
  {
    goPackagePath = "github.com/pkg/errors";
    fetch = {
      type = "git";
      url = "https://github.com/pkg/errors";
      rev = "27936f6d90f9c8e1145f11ed52ffffbfdb9e0af7";
      sha256 = "0yzmgi6g4ak4q8y7w6x0n5cbinlcn8yc3gwgzy4yck00qdn25d6y";
    };
  }
  {
    goPackagePath = "github.com/pkg/profile";
    fetch = {
      type = "git";
      url = "https://github.com/pkg/profile";
      rev = "f6fe06335df110bcf1ed6d4e852b760bfc15beee";
      sha256 = "0gwjm63y0zl55958yl3cii0pr93nvipwkhhgrdx05izk3jq4l902";
    };
  }
  {
    goPackagePath = "github.com/problame/go-netssh";
    fetch = {
      type = "git";
      url = "https://github.com/problame/go-netssh";
      rev = "b13d3b7d44e02d3ec7af19812d08e9738d7ce002";
      sha256 = "00bh944l0m9jbhbd775vl46g94prhqdkk79r33zvs7ki0c2kr4jg";
    };
  }
  {
    goPackagePath = "github.com/prometheus/client_golang";
    fetch = {
      type = "git";
      url = "https://github.com/prometheus/client_golang";
      rev = "b0f4d8e1d513eb4dcb62defe0a3cdaed60672fcb";
      sha256 = "1qj4gwsc9nknqsry9f3f2j6nh111b9xvfk0s9b5cwlq488by1kmp";
    };
  }
  {
    goPackagePath = "github.com/prometheus/client_model";
    fetch = {
      type = "git";
      url = "https://github.com/prometheus/client_model";
      rev = "fd36f4220a901265f90734c3183c5f0c91daa0b8";
      sha256 = "1bs5d72k361llflgl94c22n0w53j30rsfh84smgk8mbjbcmjsaa5";
    };
  }
  {
    goPackagePath = "github.com/prometheus/common";
    fetch = {
      type = "git";
      url = "https://github.com/prometheus/common";
      rev = "1ba88736f028e37bc17328369e94a537ae9e0234";
      sha256 = "00008pczafy982m59n1j31pnp41f4grbc2c40jccp52xg3m5klmr";
    };
  }
  {
    goPackagePath = "github.com/prometheus/procfs";
    fetch = {
      type = "git";
      url = "https://github.com/prometheus/procfs";
      rev = "5867b95ac084bbfee6ea16595c4e05ab009021da";
      sha256 = "1rahdk62ajj4zpfb3mgzjqip773la9fb0m87m7s9a0b39l3fmzvr";
    };
  }
  {
    goPackagePath = "github.com/spf13/cobra";
    fetch = {
      type = "git";
      url = "https://github.com/spf13/cobra";
      rev = "67fc4837d267bc9bfd6e47f77783fcc3dffc68de";
      sha256 = "1k7dq78fjz94lzifsprkmiv93swwzwcbg1vd64v20wvnga8v254b";
    };
  }
  {
    goPackagePath = "github.com/spf13/pflag";
    fetch = {
      type = "git";
      url = "https://github.com/spf13/pflag";
      rev = "24fa6976df40757dce6aea913e7b81ade90530e1";
      sha256 = "0rf6prz6gl0l1b3wijzdgq887cdwigvzxvz6gqbm5l8pkq3fx1m9";
    };
  }
  {
    goPackagePath = "github.com/theckman/goconstraint";
    fetch = {
      type = "git";
      url = "https://github.com/theckman/goconstraint";
      rev = "93babf24513d0e8277635da8169fcc5a46ae3f6a";
      sha256 = "1ngc5zc409smdbl5yj84ynzzcqk3g070bxwhl9jy03bz0ic4sfxc";
    };
  }
  {
    goPackagePath = "github.com/zrepl/yaml-config";
    fetch = {
      type = "git";
      url = "https://github.com/zrepl/yaml-config";
      rev = "08227ad854131f7dfcdfb12579fb73dd8a38a03a";
      sha256 = "17iab2z608gl47cq9cq76a8220gsjpjvl5xjxkdvyply0nh847lp";
    };
  }
  {
    goPackagePath = "golang.org/x/net";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/net";
      rev = "a4d6f7feada510cc50e69a37b484cb0fdc6b7876";
      sha256 = "039jlg998drqyz9mamn0sq8c09q1h7q4jr1520s0d5s3ihg02y3j";
    };
  }
  {
    goPackagePath = "golang.org/x/sync";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/sync";
      rev = "112230192c580c3556b8cee6403af37a4fc5f28c";
      sha256 = "05i2k43j2d0llq768hg5pf3hb2yhfzp9la1w5wp0rsnnzblr0lfn";
    };
  }
  {
    goPackagePath = "golang.org/x/sys";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/sys";
      rev = "a5b02f93d862f065920dd6a40dddc66b60d0dec4";
      sha256 = "08x9lszx1bwgv8bsfskqx200kqbaa542kyzli88zfxnc61smgksm";
    };
  }
  {
    goPackagePath = "golang.org/x/text";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/text";
      rev = "342b2e1fbaa52c93f31447ad2c6abc048c63e475";
      sha256 = "0flv9idw0jm5nm8lx25xqanbkqgfiym6619w575p7nrdh0riqwqh";
    };
  }
  {
    goPackagePath = "google.golang.org/genproto";
    fetch = {
      type = "git";
      url = "https://github.com/google/go-genproto";
      rev = "b515fa19cec88c32f305a962f34ae60068947aea";
      sha256 = "0j5yvig95wvn7zyfw07fh54s6kk30z0xfwgqbwf8z7iqcm93xci1";
    };
  }
  {
    goPackagePath = "google.golang.org/grpc";
    fetch = {
      type = "git";
      url = "https://github.com/grpc/grpc-go";
      rev = "ab909771a093a95d8634391debbafe3aea44f688";
      sha256 = "1r1ckl0hfysl6989aqbhd3wlbxrrr2ycxiscn5b0lwivrdazz4qk";
    };
  }
]
